### ISSUE TITLE
Long app name display issue

### ISSUE THREAD

**Issue by nikwen** [bhdouglass/ubuntu-appstore#29]
Check out: https://uappexplorer.com/apps?q=fordonskombinationskalkylator :wink:

**Comment by bhdouglass** [comment]
Fixed! It now does some word wrap in those situations.

**Comment by nikwen** [comment]
Thanks. :)

**Comment by nikwen** [comment]
I still see some issues on mobile though. Let me upload a screenshot later. ;)

**Comment by bhdouglass** [comment]
Send them my way and I'll get them fixed! :)

**Comment by nikwen** [comment]
![screenshot20150505_170451188](https://cloud.githubusercontent.com/assets/3309657/7476574/ae412ef0-f34e-11e4-904a-3c1efa6be2b4.png)

Here you go. ;)

**Comment by bhdouglass** [comment]
Just fixed this!

**Comment by nikwen** [comment]
Great, thanks. :)
